<center><h4><b>PHY4905/5905: Computational Physics – Spring 2022</b></h4></center>
<center><h4><b>Homework #7: Numerical Linear Algebra</b></h4></center>
<center><h4><b>Code Author: Pratiksha Balasaheb Gaikwad</b></h4></center>
<hr style="height:2px;border-width:0;color:orange;background-color:orange">
<hr style="height:2px;border-width:0;color:blue;background-color:blue">

**1. Gaussian elimination with pivoting:**  


(a) Consider the following system of linear equations, written in the matrix form
$$\textbf{A x = v}:$$

$$
\begin{pmatrix}
0 & 1 & 4 & 1\\
3 & 4 & -1 & -1\\
1 & -4 & 1 & 5\\
2 & -2 & 1 & 3
\end{pmatrix}
\begin{pmatrix}
w \\ x \\ y \\ z 
\end{pmatrix}
=
\begin{pmatrix}
-4 \\ 3 \\ 9 \\ 7
\end{pmatrix}
$$

Solve this matrix equation for the unknown variables using Gaussian elimination with pivoting. You may start by using the Gaussian elimination algorithm from class (or the 'gausselim.py' script from Newman) and modify it to include
pivoting.  

(b) Compare your answer with the results you obtain using the 'numpy.linalg.solve()' function instead of your own algorithm.

In [3]:
import numpy as np
from copy import copy


In [16]:
def pivot(_A,_v):   
    """
    Function for implementation of pivoting method.
    
    Inputs: A (NxN matrix as numpy array) 
            v (length-N numpy array)
            
    
    Returns: 
    New A (NxN matrix as numpy array) 
    New v (length-N numpy array)
    after pivoting.
    """
    N = len(_v)
    
    for m in range(N-1):
        maxn = _A[m][m] # initiate maximum number with diagonal element of current row
        indx = m       # initiate index for maximum number with that of current row
  
        # Loop to find out index of row whose m^th  element has the largest absolute value.
        for i in range(m+1,N):
            if abs(_A[i][m]) > maxn:
                maxn = abs(_A[i][m])
                indx = i
        #print(indx, maxn, "\n")
        
        _A[[m,indx]] = _A[[indx,m]] # swap rows
        _v[[m,indx]] = _v[[indx,m]] # swap rows
        
        
    print("\n>>> Pivoting done!\n")
    print(f"NEW A={_A} \n")
    print(f"NEW v={_v}")
    
    return _A, _v

In [17]:
def ge_solve(A, v):
    """
    Simple implementation of Gaussian elimination
    
    Based on gausselim.py from Newman,
    adapted by L. Blecha, later adapted by Pratiksha G.
    Inputs: A (NxN matrix as numpy array) 
            v (length-N numpy array)    
    
    
    Returns: x (length-N array that solves A x = v)
    """
    
    # Define new, distinct variables _A, _v to avoid
    # modifying the global variables (A, v)
    # that are passed to the function
    _A = copy(A)
    _v = copy(v)
    
    N = len(_v)
    
    if _A.shape[0] != N or _A.shape[1] != N:
        print("Error: array shape mismatch in ge_solve:")
        print(_A.shape, _v.shape)
        return []

    diag = np.diag(A)
    if 0.0 in diag: # check if any diagonal element is zero
        _A, _v = pivot(A,v) # do pivioting using pivot function


    # Gaussian elimination
    for m in range(N):

        # Divide by the diagonal element
        div = _A[m,m]
        _A[m,:] /= div
        _v[m] /= div

        # Now subtract from the lower rows
        for i in range(m+1,N):
            mult = _A[i,m]
            _A[i,:] -= mult*_A[m,:]
            _v[i] -= mult*_v[m]

    # Backsubstitution
    x = np.empty(N,float)
    #print(N)
    for m in range(N-1,-1,-1):
        x[m] = _v[m]
        #print(m)
        for i in range(m+1,N):
            #print(m,i)
            x[m] -= _A[m,i]*x[i]

    #print(x)
    return x

In [9]:
A = np.array([[ 0,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]],float)
v = np.array([ -4, 3, 9, 7 ],float)

# perform the Gaussian elimination with pivoting to solve
print("Solving matrix equation A x = v using Gaussian elimination.\n")
print(f"A={A}")
print(f"v={v}")

# x is the solution to the system Ax = v using own code
x = ge_solve(A, v)

print("\nThe solution is")
print(f"x={x}")



Solving matrix equation A x = v using Gaussian elimination.

A=[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
v=[-4.  3.  9.  7.]

>>> Pivoting done!

NEW A=[[ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 0.  1.  4.  1.]
 [ 2. -2.  1.  3.]] 

NEW v=[ 3.  9. -4.  7.]

The solution is
x=[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


<center><h3><b>Using 'numpy.linalg.solve(A,v)'</h3></center></b>

In [10]:
# lib_x is the solution to the system Ax = v using the numpy library function
lib_x = np.linalg.solve(A,v)
print("\nThe solution is")
print(f"x={lib_x}")


The solution is
x=[ 1.61904762 -0.42857143 -1.23809524  1.38095238]


<center><h3><b>Comparing with x = numpy.linalg.solve(A,v) function for Ax = v</h3></center></b>

In [11]:
print("\nUsing np.array_equal: ", np.array_equal(x, lib_x))
print("\nUsing np.allclose: ", np.allclose(x, lib_x))


result = np.subtract(x, lib_x)
print ('\n\nThe difference b/w both solutions =', result)


Using np.array_equal:  False

Using np.allclose:  True


The difference b/w both solutions = [2.22044605e-16 0.00000000e+00 0.00000000e+00 0.00000000e+00]


>So there is a difference of python precision zero values. That shows that our own code and the **numpy.linalg.solve()** gives the same results.